### ISSUE TITLE
Houdini Error

### ISSUE THREAD

**Issue by AssetMana** [brosquinha/houdini-bot-plugin#1]
Hello, when attempting to use your plugin in Houdini  I received an error message. Any help is greatly appreciated.
houdini_login_1     | Postgres is up - executing command
houdini_login_1     | 2024-02-12 05:41:27,522 [INFO ]  Booting Houdini
houdini_login_1     | 2024-02-12 05:41:27,586 [INFO ]  Login server started
houdini_login_1     | 2024-02-12 05:41:27,591 [INFO ]  Loaded 6 dance tracks
houdini_login_1     | 2024-02-12 05:41:27,596 [INFO ]  Loaded 27 characters
houdini_login_1     | 2024-02-12 05:41:27,630 [INFO ]  Loaded 509 ninja cards
houdini_login_1     | 2024-02-12 05:41:27,633 [INFO ]  Loaded 3 starter decks
houdini_login_1     | 2024-02-12 05:41:27,752 [INFO ]  Loaded 96 igloos
houdini_login_1     | 2024-02-12 05:41:27,752 [INFO ]  Loaded 1384 furniture items
houdini_login_1     | 2024-02-12 05:41:27,752 [INFO ]  Loaded 8 igloo locations
houdini_login_1     | 2024-02-12 05:41:27,752 [INFO ]  Loaded 24 igloo flooring
houdini_login_1     | 2024-02-12 05:41:28,219 [INFO ]  Loaded 5325 clothing items
houdini_login_1     | 2024-02-12 05:41:28,234 [INFO ]  Loaded 204 postcards
houdini_login_1     | 2024-02-12 05:41:28,238 [INFO ]  Loaded 0 filter words
houdini_login_1     | 2024-02-12 05:41:28,259 [INFO ]  Loaded 156 rooms (7 spawn)
houdini_login_1     | 2024-02-12 05:41:28,281 [INFO ]  Loaded 147 puffle care items
houdini_login_1     | 2024-02-12 05:41:28,282 [INFO ]  Loaded 40 puffles
houdini_login_1     | 2024-02-12 05:41:28,384 [INFO ]  Loaded 352 stamps
houdini_login_1     | 2024-02-12 05:41:28,387 [INFO ]  Multi-client support is enabled
houdini_login_1     | 2024-02-12 05:41:28,387 [INFO ]  Listening on 0.0.0.0:6112
houdini_login_1     | 2024-02-12 05:41:28,396 [INFO ]  Bot plugin loaded
houdini_login_1     | Traceback (most recent call last):
houdini_login_1     |   File "/usr/src/houdini/bootstrap.py", line 141, in <module>
houdini_login_1     |     asyncio.run(factory_instance.start())
houdini_login_1     |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
houdini_login_1     |     return runner.run(main)
houdini_login_1     |            ^^^^^^^^^^^^^^^^
houdini_login_1     |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
houdini_login_1     |     return self._loop.run_until_complete(task)
houdini_login_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
houdini_login_1     |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
houdini_login_1     |   File "/usr/src/houdini/houdini/houdini.py", line 172, in start
houdini_login_1     |     await self.plugins.setup(houdini.plugins)
houdini_login_1     |   File "/usr/src/houdini/houdini/plugins/__init__.py", line 58, in setup
houdini_login_1     |     await self.load(plugin_package)
houdini_login_1     |   File "/usr/src/houdini/houdini/plugins/__init__.py", line 84, in load
houdini_login_1     |     await plugin_object.ready()
houdini_login_1     |   File "/usr/src/houdini/houdini/plugins/bot/bot_plugin.py", line 74, in ready
houdini_login_1     |     await bot.move_to_random_room()
houdini_login_1     |   File "/usr/src/houdini/houdini/plugins/bot/penguin_bot.py", line 162, in move_to_random_room
houdini_login_1     |     await self.join_room(
houdini_login_1     |   File "/usr/src/houdini/houdini/penguin.py", line 88, in join_room
houdini_login_1     |     await room.add_penguin(self)
houdini_login_1     |   File "/usr/src/houdini/houdini/data/room.py", line 142, in add_penguin
houdini_login_1     |     await p.send_xt('jr', self.id, await self.get_string(f=stealth_mod_filter(p.id)))
houdini_login_1     |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
houdini_login_1     |   File "/usr/src/houdini/houdini/data/room.py", line 63, in get_string
houdini_login_1     |     return '%'.join([await p.string for p in filter(f, self.penguins_by_id.values())])
houdini_login_1     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
houdini_login_1     |   File "/usr/src/houdini/houdini/data/room.py", line 63, in <listcomp>
houdini_login_1     |     return '%'.join([await p.string for p in filter(f, self.penguins_by_id.values())])
houdini_login_1     |                            ^^^^^^^^
houdini_login_1     |   File "/usr/src/houdini/houdini/penguin.py", line 77, in string
houdini_login_1     |     return self.server.penguin_string_compiler.compile(self)
houdini_login_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
houdini_login_1     | AttributeError: 'NoneType' object has no attribute 'compile'

**Comment by brosquinha** [comment]
Commit [5079fe2](https://github.com/brosquinha/houdini-bot-plugin/commit/5079fe2b6a0f71bdd7f52f20d8c01447cd2ed925) should fix this issue.
